### ISSUE TITLE
Prepare easy way to have someone run drivelist for debugging

### ISSUE THREAD

**Issue by WasabiFan** [resin-io-modules/drivelist#124]
In the  course of debugging drive detection issues, it's pretty common to ask people to download the drivelist script and run it. It would be nice if there were a wiki page here (or a similar resource) with one-liners to accomplish this. I prepared something like this for Windows, if it's useful:

```cmd
@powershell -NoProfile -ExecutionPolicy Bypass -Command "(New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/resin-io-modules/drivelist/master/scripts/win32.bat')" > drivelist-win32.bat && .\drivelist-win32.bat
```

It's not exactly optimal (it saves the file before executing it) because I couldn't figure out how to execute the WSH script dynamically, but it gets the job done.

**Comment by alexandrosm** [comment]
wouldn't it be even better if in the "settings" page there was a button
("debug info") that gives you the output, makes it easy to copy clipboard?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jviotti** [comment]
Yeah, I agree with @alexandrosm. As a side thought: we could make the platform scripts output a lot more information and prefix them as YAML comments, so in the settings page, we would know much better that actually happened.

**Comment by WasabiFan** [comment]
Ah, good idea; that isn't really a drivelist feature at that point (this isn't the Etcher repo) but it would be nice either way. With that method, a lot more information could be printed from a variety of sources.

**Comment by jviotti** [comment]
I'll close this one, and lets continue discussion here: https://github.com/resin-io/etcher/issues/857

**Comment by WasabiFan** [comment]
Whoops, sorry about that; I guess I forgot to hit the correct button.
