### ISSUE TITLE
Method of getting drive size on Windows needs changing

### ISSUE THREAD

**Issue by lurch** [resin-io-modules/drivelist#142]
For all the gory details, see my comments in https://github.com/resin-io/etcher/issues/995

But in summary: `scripts/win32.bat` in this repo currently gets the size of the drive using [Win32_DiskDrive](https://msdn.microsoft.com/en-us/library/aa394132(v=vs.85).aspx) which erroneously calculates the size of the raw drive using the CHS values. While this works fine for mechanical hard drives, it doesn't work for flash media (SD cards, USB sticks, etc.) and often under-reports the actual size of the drive. [IOCTL_DISK_GET_DRIVE_GEOMETRY_EX](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365171(v=vs.85).aspx) needs to be used instead, to get the _actual_ size of the raw drive.

I believe that fixing this will fix all the problems mentioned in https://github.com/resin-io/etcher/issues/995

**Comment by jviotti** [comment]
Fixed by https://github.com/resin-io-modules/drivelist/pull/186
