### ISSUE TITLE
diskinfo[0]: unbound variable

### ISSUE THREAD

**Issue by Edudjr** [resin-io-modules/drivelist#147]
I was trying to get a list of devices every half a second, like the code below:  
```javascript
setInterval(function(){
  drivelist.list((error, drives) => {
    if (error) {
      throw error;
    }
    callback(drives);
  });
}, 500);
```

However, I was getting an error of unbound variable whenever I unplugged the usb flash drive: 
![Unbound variable](http://i.imgur.com/0adPmPl.png)

It seems that this modification to the line 29 solved my problem:
```bash
#Check for diskinfo before continuing
if [ -z "${diskinfo-}" ]; then
  continue
fi
size=${diskinfo[0]}
...
```
Could you check that?

**Comment by jviotti** [comment]
Thanks a lot for reporting this and investigating and potential solution. We're hitting this same issue on Etcher (https://github.com/resin-io/etcher/issues/1126#issuecomment-282083506), which is great. I'll push a fix today.

**Comment by Edudjr** [comment]
@jviotti great! I hope this will fix the issue :)

**Comment by jviotti** [comment]
See https://github.com/resin-io-modules/drivelist/pull/148. I fixed for Linux and OS X, and working on the Windows one, which proved to be trickier.

**Comment by jviotti** [comment]
@Edudjr I finally got the Windows VBScript working \o/ Feel free to review the PR. I'll publish a new version to npm once its merged. Thanks a lot!

**Comment by Edudjr** [comment]
@jviotti Awesome! Thanks for reviewing this issue so quickly :)
