### ISSUE TITLE
[REQ] Drive serial number

### ISSUE THREAD

**Issue by nevercast** [resin-io-modules/drivelist#15]
Hello!

I love this project, the support across all major operating systems is a big plus to me. Currently I have a project that works with raw drives and in Linux it's rather trivial because of the vast packages available to get information about hardware such as drives.

One piece of information I require is the unique serial number of the hard-drive so that I can store tags in a local database and index that hard-drive by serial so that it is identifiable in the future. There doesn't seem to be a means to query this. 

So this is my request, the unique serial number exposed with the drivelist. I've not viewed the source but I will later and offer a PR if it's a simple implementation. Otherwise this issue sits for anyone else wishing to consider it.

Thank you for this project.

**Comment by jviotti** [comment]
@nevercast Hello, thanks for reaching out and let us know your appreciation of the project :)

> I've not viewed the source but I will later and offer a PR if it's a simple implementation

The implementation is very simple, we rely on `child_process.exec` to execute different commands in each operating system (`diskutil` in OS X, grep `/proc/mounts` in GNU/Linux and `wmic` in Windows).

> One piece of information I require is the unique serial number of the hard-drive so that I can store tags in a local database and index that hard-drive by serial so that it is identifiable in the future. There doesn't seem to be a means to query this.

What would be the way to query this information outside NodeJS? Are there specific commands to get this?

**Comment by jviotti** [comment]
There is a redesign coming soon (see https://github.com/resin-io/drivelist/issues/18#issuecomment-138490990 for details), so I'll be delaying the implementation of this feature until then.

**Comment by jviotti** [comment]
I've written an easy specification for the redesign in the wiki (https://github.com/resin-io/drivelist/wiki/Drivelist-redesign-spec). Feel free to comment and contribute!

**Comment by jviotti** [comment]
@nevercast The redesign has been made. I'm happy to take a PR that implements the serial number support in the three operating systems.

**Comment by nevercast** [comment]
@jviotti Looks good! I'll leave a follow up for this in the weekend or late next week. It's unlikely I'll even get started before then. Cheers.

**Comment by jviotti** [comment]
@nevercast Sounds great! Let me know if I can help with any OS!

**Comment by jhermsmeier** [comment]
Closing due to staleness; feel free to re-open if needed

**Comment by prashantbodh099** [comment]
I wanted to do some filtering of devices based on the drive serial number, So it will be great if I can get that from drivelist module.   Do we have any progress regarding this issue?
