### ISSUE TITLE
Linux mount path contains invalid characters

### ISSUE THREAD

**Issue by ninox92** [resin-io-modules/drivelist#152]
I have a USB named `ECG REC`

When listing drives in Linux this results in a mountpoint path of:
/media/mypath/ECG\\\040REC

**Comment by lurch** [comment]
Thanks for the report. Could you confirm that the updated version in #153 works properly now? :-)

**Comment by jviotti** [comment]
I've published @lurch 's fix as v5.0.17

**Comment by ninox92** [comment]
Fix comfirmed, can close!
Thanks for the quick fix <3
