### ISSUE TITLE
Does not see RAM drives and subst-powered virtual drives

### ISSUE THREAD

**Issue by Marat-Tanalin** [resin-io-modules/drivelist#158]
The **drivelist** module does not see **RAM drives** (e.&thinsp;g. created by _QSoft RAMDrive Enterprise_) and **virtual drives** (folder aliases with assigned drive letters) created by Windows subst application (e.&thinsp;g. created by _Denwer_ WAMP kit).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2bd9)

**Comment by jviotti** [comment]
Hi @Marat-Tanalin,

This project is focused on listing physical drives (removable and non-removable), so I'm afraid this is out of scope at the moment.

That being said, I'd accept a PR to show these under a certain flag, or something like that, however we should implement this for all platforms if so.

**Comment by Marat-Tanalin** [comment]
In Windows, a [solution](http://stackoverflow.com/a/28909820) based on using [WMIC](https://msdn.microsoft.com/en-us/library/aa394531) works fine.

**Comment by jviotti** [comment]
This module used to call `wmic`, however parsing back the WMIC table and extending its results with the extra things this module does proved to be a pain. 

As a side note, we're working on moving the Windows part to C++ to workaround a known [WMI size detection issue](https://github.com/resin-io-modules/drivelist/issues/142), so adding this functionality using the C++ WMI libraries would be great.

**Comment by Marat-Tanalin** [comment]
Is this just about programming pain or about that WMIC results might be unreliable?

Are you aware of Node.js modules focused on listing all _logical_ drives? Thanks.

**Comment by jviotti** [comment]
> Is this just about programming pain or about that WMIC results might be somewhat unreliable / inconsistent?

Both. Parsing back WMIC results was a programming pain, however the choice to go for C++ is because of a WMI limitation (it returns incorrect sizes in some edge cases, and we can't circumvent that without interacting with low level Windows C APIs to get the correct ones).

> Are you aware of Node.js modules focused on listing all logical drives? Thanks.

I'm not aware of any, sorry. If listing is all you need, the calling WMIC as a child process and parsing back the result should be a great way to go. Feel free to inspect older commits on this project if you want to borrow existing WMIC output parsing code :)

**Comment by jviotti** [comment]
See https://github.com/resin-io-modules/drivelist/blob/51e5d75c83d9fc1a97503a2c6322e3080a7d3d13/lib/win32.coffee

**Comment by Marat-Tanalin** [comment]
OK, thanks. Looking forward for a native Node-module-level solution.

**Comment by jviotti** [comment]
@Marat-Tanalin Take a look at the tip of master! :)

**Comment by Marat-Tanalin** [comment]
@jviotti Do you mean this issue is fixed by reimplementing some parts of the module in C++ (#178, a09f993)? If so, when will that version be available in a ready-to-use form via npm? Thanks.

**Comment by jviotti** [comment]
I mean that after the C++ re-write, fixing this issue is much easier, maybe by providing an option, or by listing all connected drives and adding a `type` property.

We're making some final changes and polishing some rough edges, but I'd expect a version to be published to npm next week.

**Comment by jhermsmeier** [comment]
Reopening this, as we've received a new report of the scan not working with virtual drives created via the `subst` command.

**Comment by Page-** [comment]
Is there any word on thi?  As `SUBST` drives seem to have worked on 5.0.20 but broke somewhere in a patch release between then and 5.0.27 and means I can't use the latest etcher versions

**Comment by jhermsmeier** [comment]
I'm working on it at the moment, but that'll likely not make it into the upcoming release. But if it does work with 5.0.20, we could look at downgrading to that for the next release.

**Comment by jhermsmeier** [comment]
Closing, as this has been fixed in #243
