### ISSUE TITLE
Detect when a drive has been inserted

### ISSUE THREAD

**Issue by harrynewsome** [resin-io-modules/drivelist#160]
Firstly, thanks for the module!

Is it possible to listen for when a drive has been inserted into the computer without setting a timeout that would check every x seconds, for example to listen for when a USB has been inserted?

**Comment by lurch** [comment]
I think what you're asking for is "a level above" what `drivelist` is designed for, and calling drivelist repeatedly (and then looking for the difference in results) is probably your best option?
IIRC that's what we do in Etcher, right @jviotti ?

**Comment by jviotti** [comment]
Yeah, polling is probably the way to go. We could implement an event based interface on top of this module, but that would use polling anyway.

You might want to take a look at RxJS (https://github.com/resin-io/etcher/blob/master/lib/gui/modules/drive-scanner.js#L41), which makes this task particularly elegant.

**Comment by harrynewsome** [comment]
That's perfect! Thank you both @lurch @jviotti

**Comment by lurch** [comment]
By coincidence, I spotted this earlier today: https://www.npmjs.com/package/drivelist-scanner

**Comment by harrynewsome** [comment]
Ah that's interesting, thanks! 

@lurch
