### ISSUE TITLE
Getting an error when using drivelist on Windows

### ISSUE THREAD

**Issue by MaxJeong** [resin-io-modules/drivelist#167]
After I installed drivelist and using the example code in my Electron app, I got the following error:

Uncaught Error: process.binding is not supported
    at Object.process.binding (index.js:30296)
    at Object.<anonymous> (index.js:46258)
    at Object.312._process (index.js:46732)
    at s (index.js:1)
    at index.js:1
    at Object.275.../package.json (index.js:35949)
    at s (index.js:1)
    at index.js:1
    at Object.274../execute (index.js:35884)
    at s (index.js:1)
    at index.js:1
    at Object.<anonymous> (index.js:13)
    at Object.1../listWidgets.js (index.js:649)
    at s (index.js:1)
    at index.js:1
    at Object.<anonymous> (index.js:4534)

Is this just an Electron thing? Or is there a workaround?

**Comment by lurch** [comment]
Could you show how you're calling drivelist? For comparison, this is how we do it in Etcher (also an Electron app) https://github.com/resin-io/etcher/blob/master/lib/gui/modules/drive-scanner.js

@jviotti Did we need to do anything special to get the platform-scripts bundled correctly?

@MaxJeong drivelist isn't pure-NodeJS but instead relies on executing platform-specific shell scripts https://github.com/resin-io-modules/drivelist/tree/master/scripts  (which is something we're planning to change in future by rewriting it as a C++ node module).

**Comment by jviotti** [comment]
At first sight, that looks like an issue unrelated to `drivelist`, given `process.binding` is not used at all by this module. @MaxJeong Maybe there is something else going on in your Electron app? 

Can you link us to a branch of this app that we can test ourselves, or create a small reproducible example?

**Comment by MaxJeong** [comment]
@lurch I'm literally just using the example provided in the doc. So I'm calling drivelist like this:

const drivelist = require('drivelist');

drivelist.list((error, drives) => {
        if (error) {
            throw error;
        }

        drives.forEach((drive) => {
            console.log(drive);
        });
    });

The problem is, I get the process.binding error as soon as I require drivelist. There doesn't seem to be anything wrong with the example code (at least not yet for me since the error in thrown in require drivelist).

**Comment by lurch** [comment]
> The problem is, I get the process.binding error as soon as I require drivelist.

I assume you've also got `drivelist` listed in your `dependencies` in `package.json`, and it's locally installed into your `node_modules` directory?

**Comment by jviotti** [comment]
@MaxJeong That's really strange. Can you please create a small gist that reproduces the issue? I'd love to investigate further.

**Comment by jhermsmeier** [comment]
@MaxJeong is this still an issue for you? I'll close this for now, due to inactivity, and us not being able to reproduce. If this is still a problem, feel free to re-open this!
