### ISSUE TITLE
Crash on electron app opening on Windows.

### ISSUE THREAD

**Issue by MathiasBojda** [resin-io-modules/drivelist#205]
Hi.
I get this issue when trying to open an Electron app on Windows 7 Enterprise Via Bootcamp, It works fine on Mac however.

See image:
http://imgur.com/a/L6Dvh

**Comment by jviotti** [comment]
That is extremely weird. Do you have a reproducible repo I can test myself?

**Comment by lurch** [comment]
I wonder if this might be another spaces-in-the-filepath issue? @MathiasBojda Could you try re-running your test from a folder that doesn't contain any spaces in it's path?

**Comment by MathiasBojda** [comment]
OK, Thanks! - Will test today, and sorry the repo i have is a private one, which is owned by a third party, so i cannot give that out.

**Comment by jhermsmeier** [comment]
@MathiasBojda is this still an issue?

**Comment by MathiasBojda** [comment]
@jhermsmeier Yes. tried removing spaces from the path, etc. It still had the problem. Sorry for not getting back.

**Comment by jhermsmeier** [comment]
Looks like this is actually an issue with `electronify` not bundling the native module bindings (or bundling them when it shouldn't), or more generally speaking; the native bindings not being available from where they're being read from.

Closing, as this doesn't appear to be an issue with `drivelist` itself, but the build configuration / mechanism used there.
