### ISSUE TITLE
Suggestion: Could report both errors and drives

### ISSUE THREAD

**Issue by lurch** [resin-io-modules/drivelist#207]
As suggested in https://github.com/resin-io/etcher/issues/1687#issuecomment-322154982
It might be nice to have drivelist return both errors (so that we can report that something went wrong) _and_ the drives that `drivelist` **did** detect, so that if there's e.g 5 drives on a system, and we encounter an error while just scanning one of the drives, we can still get information about the other 4 drives that we _were_ able to scan without errors.

**Comment by jhermsmeier** [comment]
Might also be good to have an error property on the drive objects themselves, containing the error that happened for that particular device, while using the callback's error argument for top level errors that prevent listing of drives completely.

**Comment by jhermsmeier** [comment]
Added in #243
