### ISSUE TITLE
couldn't scan the drives permission error

### ISSUE THREAD

**Issue by emarch06** [resin-io-modules/drivelist#208]
Hi,

I'm trying to user Etcher on Windows 10 64 bits Build 14393.1480.
On some workstations, I've got the error "couldn't scan the drives: permission error"

I think it's related to a setting in my windows installation, but how can I get a more explicit error?

Thanks and regards
Eric

**Comment by lurch** [comment]
See the comment from @jviotti in https://github.com/resin-io/etcher/issues/1693

**Comment by emarch06** [comment]
Hi,

note that I managed to wrote the same SD card / image under ubuntu 16.04

I removed all the USB sticks, SD cards from my laptop, then launched etcher from cmd. Here's the log:

[drivelist] Initializing scanner
[drivelist] Initializing COM
[drivelist] Initializing COM security levels
[drivelist] Creating connection instance
[drivelist] Connecting to server
[drivelist] Setting proxy security levels
[drivelist] Interpreting error 0x0
[drivelist] Getting list of drives from WMI
[drivelist] Getting id
[drivelist] Processing \\.\PHYSICALDRIVE0
[drivelist] Getting caption
[drivelist] Getting disk information
[drivelist] Opening handle on \\.\PHYSICALDRIVE0
[drivelist] Getting drive geometry
[drivelist] Getting system volume drive letter
[drivelist] Getting available volumes
[drivelist] Getting volume type
[drivelist] Checking if volume has filesystem
[drivelist] Getting device number
[drivelist] Checking if disk is writable
[drivelist] Getting volume type
[drivelist] Checking if volume has filesystem
[drivelist] Getting device number
[drivelist] Interpreting error 0x80070005

**Comment by jviotti** [comment]
Hi @emarch06 ,

What Etcher version are you on? We've been fixing similar issues recently. Some fixes landed on v1.1.2, and some are in `master`, but have not been released yet. Can you try the following nighty build: https://resin-nightly-downloads.s3.amazonaws.com/etcher/2017-08-21/1.1.2%2Bf9d7dd2/Etcher-Setup-1.1.2%2Bf9d7dd2-x64.exe?

**Comment by emarch06** [comment]
Hi,

I'm using the 1.1.2 indeed.
I tried your build and I had the same result and same log :-(

Note that the computer uses bitlocker with automatic drive unlock at boot (no pin entered)

**Comment by jviotti** [comment]
Hi @emarch06 ,

I've been investigating this issue, and I know what's going on, but not why. The permissions error is thrown when opening a handle on the volume. According to [the docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx):

> The most commonly used values are GENERIC_READ, GENERIC_WRITE, or both (GENERIC_READ | GENERIC_WRITE). For more information, see Generic Access Rights, File Security and Access Rights, File Access Rights Constants, and ACCESS_MASK.
> If this parameter is zero, the application can query certain metadata such as file, directory, or device attributes without accessing that file or device, even if GENERIC_READ access would have been denied.

I can confirm that `GENERIC_READ` throws permissions errors on system volumes (e.g. `C:`), however we are using `0` everywhere (I double checked just in case), which should give us certain access even if `GENERIC_READ` would have been denied.

I don't understand why `0` gives permission errors in your case. I researched a bit, but I can't find any other case on the web.

Is there are specific tweaked permissions / access control policies that could be interfering? If so, can you point me to it? It'd be great if I manage to reproduce your exact same scenario.

**Comment by jviotti** [comment]
Do you get a different error message if you run it as administrator?

**Comment by emarch06** [comment]
Hi,

I've got the same error as administrator :-(

I tried to look at settings, but nothing shocked me on the computer.
How can I help you reproduce this issue? Do you want an extract of the local computer policy?

Since I don't know if the error would happen on external drives (SD card, USB stick), could you workaround this issue by ignoring the drive on failure.
Then on select drive, you'll list only drives you can access to?

I can test scripts or any builds if it can help ;)

Thanks and regards
Eric

**Comment by lurch** [comment]
> could you workaround this issue by ignoring the drive on failure.
Then on select drive, you'll list only drives you can access to?

Yeah, I already suggested that in #207 ;-)

**Comment by SunSeaAndPalms** [comment]
Facing the same with v1.1.2. Is there a workaround today?

**Comment by matthewrfellows** [comment]
I'm using Etcher 1.1.2 on Windows 7 Home 64-bit, and had the same problem. Hopefully this solution, or something similar, will help others:
I noticed that I had a Q: (Protected) Drive called "Microsoft Office 2010 click-to-run". In order to get rid of that, you have to uninstall the program with that same name. After that, though, the Etcher problem went away and I was able to write to the SD card.

**Comment by jhermsmeier** [comment]
Thanks for the info @matthewrfellows! Yet another thing we'll need to test for.

**Comment by sasclar** [comment]
Same error with windows 10 x64 and etcher 1.2.1
@matthewrfellows 's solution solved the problem, the Q: drive had to be removed !
Thanks ! ;)

**Comment by bandita137** [comment]
Similar issue, slightly different solution: Win7 / Etcher 1.2.1 giving me permission error on start. 

I had a lot of directories made to drives using the "subst" command. By removing all of them with e.g. "subst /d x:" I got rid of the permission error.

It would be great to get the drive letter displayed in the error message to see which volumes are problematic - instead of googling I'd immediately could have figured out the issue myself.

**Comment by jhermsmeier** [comment]
This has been fixed in #243 and will ship in the next Etcher release :)

**Comment by protogun** [comment]
As @sasclar said, you need to remove the Q: drive if existing. Effectively, I've installed Office Starter 2010 and it mount a Q: drive.

The only way is to uninstall Office Starter (what a piece of sh..!).

Regards
