### ISSUE TITLE
Error in response to system.storage.getInfo: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Arti3DPlayer** [resin-io-modules/drivelist#210]
I get this error on Windows 10:

> Error in response to system.storage.getInfo: TypeError: Path must be a string. Received undefined

```
(unknown) TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at dirname (path.js:716:5)
```

```
drivelist.list(function (error, drives) {
         console.log(error)
          console.log(drives)
});
```

Tested on MAC and Linux works well. Version: 5.1.5

**Comment by Arti3DPlayer** [comment]
I'm using webpack, so I can't show detailed debug, but problem in this line:

https://github.com/resin-io-modules/drivelist/blob/2c77f2bfa86b1aba802f834fa8dd7f97179236ee/lib/drivelist.js#L53

**Comment by Arti3DPlayer** [comment]
```
→ Z:\Jscode\rf_configurator\build\RaceFlight\win64\build\drivelist.node
 → Z:\Jscode\rf_configurator\build\RaceFlight\win64\build\Debug\drivelist.node
 → Z:\Jscode\rf_configurator\build\RaceFlight\win64\build\Release\drivelist.node
 → Z:\Jscode\rf_configurator\build\RaceFlight\win64\out\Debug\drivelist.node
 → Z:\Jscode\rf_configurator\build\RaceFlight\win64\Debug\drivelist.node
 → Z:\Jscode\rf_configurator\build\RaceFlight\win64\out\Release\drivelist.node
 → Z:\Jscode\rf_configurator\build\RaceFlight\win64\Release\drivelist.node
 → Z:\Jscode\rf_configurator\build\RaceFlight\win64\build\default\drivelist.node
 → Z:\Jscode\rf_configurator\build\RaceFlight\win64\compiled\8.1.4\win32\x64\drivelist.node
    at bindings (chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:135127:9)
    at Object.exports.list (chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:135010:5)
    at new deviceNotFoundCtrlFn (chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:206317:19)
    at Object.instantiate (chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:31876:14)
    at $controller (chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:37632:28)
    at Object.<anonymous> (chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:100493:28)
    at chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:28358:18
    at invokeLinkFn (chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:37194:9)
    at nodeLinkFn (chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:36591:11)
    at compositeLinkFn (chrome-extension://dgandikapbplbmakkdaolhidnijdkkfp/app/bundle.js:35856:13) 
```

**Comment by jviotti** [comment]
Hi @Arti3DPlayer ,

The Windows side of this module was written in C++, so webpack will not work there. You could compile the code in a Windows machine, and then manually place the `.node` file in the place where the final bundle looks for it.

I'm closing this, since I don't think webpack will ever play well with this module given the native code we have (except for the manual workaround described above)

**Comment by Arti3DPlayer** [comment]
@jviotti problem that if I even put drivelist.node into `/out/out/Release/drivelist.node` it can't see it :(

**Comment by jviotti** [comment]
Can you try `Z:\Jscode\rf_configurator\build\RaceFlight\win64\build\drivelist.node`?

**Comment by Arti3DPlayer** [comment]
@jviotti Not sure, I leave this, and use https://msdn.microsoft.com/en-us/library/aa394173(v=vs.85).aspx

for win32 case

I don't know know why you use external script:(

**Comment by kennyhyun** [comment]
BTW, I had this same .node file was not found.

```
Error: Could not locate the bindings file. Tried:
```

but after I ran this manually, (I was using yarn classic and 10.0.0 )

```
npm rebuild drivelist
```

this build .node file and it stopped complaining.

not sure why it didn't build while initial installation
