### ISSUE TITLE
USB Flash drive detected as system drive on macOS

### ISSUE THREAD

**Issue by netmute** [resin-io-modules/drivelist#213]
This is the output of `diskutil info /dev/disk2`

  ```
   Device Identifier:        disk2
   Device Node:              /dev/disk2
   Whole:                    Yes
   Part of Whole:            disk2
   Device / Media Name:      Flash Disk

   Volume Name:              Not applicable (no file system)
   Mounted:                  Not applicable (no file system)
   File System:              None

   Content (IOContent):      FDisk_partition_scheme
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 USB
   SMART Status:             Not Supported

   Disk Size:                4.0 GB (4009754624 Bytes) (exactly 7831552 512-Byte-Units)
   Device Block Size:        512 Bytes

   Read-Only Media:          No
   Read-Only Volume:         Not applicable (no file system)

   Device Location:          External
   Removable Media:          Fixed

   Virtual:                  No
   OS 9 Drivers:             No
   Low Level Format:         Not supported
```

`Removable Media` is reported as `Fixed`, darwin.sh then wrongly assumes this must be a system disk (line 77).

Might going for `Device Location` be more reliable? If it is `External` it should be safe to write to.

**Comment by jviotti** [comment]
Hi @netmute,

We consider similar cases in the past. Most USB drives are not considered "Fixed" (seems to happen only in some cases), and relying on "Device Location" means that external USB hard drives, for example, are considered as "removable," which is precisely what we want to avoid.

**Comment by netmute** [comment]
I agree having a few flash drives falsely show up as system drives is more desirable than the other way around. Thank you for the clarification.
