### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/drivelist#214]
```
Error: Command failed: /var/folders/s5/z_6rdp5s6m19rhls6fjlyl0x4qx8v1/T/drivelist-d81d2a27bd18.sh
/var/folders/s5/z_6rdp5s6m19rhls6fjlyl0x4qx8v1/T/drivelist-d81d2a27bd18.sh: fork: Resource temporarily unavailable
(code 128, signal none)
at ChildProcess.exithandler (child_process.js:223:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:885:16)
at Socket.<anonymous> (internal/child_process.js:334:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by lurch** [comment]
Where does `/var/folders/s5/` come from?

**Comment by jhermsmeier** [comment]
That's what `os.tmpdir()` on Mac OS looks like:
```js
> os.tmpdir()
'/var/folders/_m/xht9586n6791b9p_c8x4k53m0000gn/T
```

**Comment by robinwassen** [comment]
Same issue in etcher: https://github.com/resin-io/etcher/issues/1495

**Comment by robinwassen** [comment]
We have received error reports from macOS 10.10, 10.11 and 10.12 regarding this issue. So it is not connected to a specific version of macOS.

**Comment by robinwassen** [comment]
Common denominator seems to be that they have left the application running drivelist open for a very long time.

Probably something that does not clean up properly.

**Comment by lurch** [comment]
I wonder if #238 might have fixed this?

**Comment by jhermsmeier** [comment]
I think this was more related to #190, which was subsequently fixed in https://github.com/resin-io-modules/drivelist/pull/191 – and we haven't seen any reports of this happening since, so going to close this
