### ISSUE TITLE
lodash dependency adds 5MB to drivelist

### ISSUE THREAD

**Issue by robinwassen** [resin-io-modules/drivelist#215]
Would like to start with saying thanks for the module! Really appreciated the effort by @jhermsmeier to create native bindings rather than using the script approach for Windows, works so much better.

I started to investigate ways for us to lower the application size of our Electron-app and started by listing the largest node modules that we use.

One of those is lodash that is 5MB which is a dependency of drivelist, it is listed as a production dependency and is therefore included in the final build of the application.

lodash is used in the script output parser (parse.js) to provide 10 convenience functions when parsing the output.

**The approaches that I see would solve this problem are:**
- (quickfix) Include only the built lodash file instead of as a node module
- Replace the usage of lodash in parse.js
- Replace the javascript script output parsing by calling native modules with V8 bindnings (#172)

Would the quickfix be considered as acceptable? I think that we can reduce the lodash dependency from ~5MB to ~4KB by including the .js file instead of using the idiomatic way of including it as a node module.

**Comment by robinwassen** [comment]
Performed some benchmarks on the effects of using lodash via npm or vendoring.

Command to install dependencies: `npm install --production`
Branch: master

Windows, NodeJS 6.11.3, npm 5.0.3:
- lodash via npm, total dependencies size: 4.5MB
- lodash vendored, total dependencies size:  2.0MB

macOS, NodeJS 6.11.1, npm 3.10.10
- lodash via npm, total dependencies size: 6.4MB
- lodash via vendor, total dependencies size: 2.0MB

Total dependencies size is measured by du and adding the node_modules and vendor directory sizes together.

I am not sure why the lodash file size is greater on macOS since it seems to be the identical amount of files, guess it has something to do with the file system and many small files.

**Comment by mceachen** [comment]
fwiw parse.js uses 10 different lodash functions, but each one is a one-liner.

**Comment by jhermsmeier** [comment]
Closed in #235
