### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by danao-realityi** [resin-io-modules/drivelist#220]
Hello, I am trying to run the starter code in the documentation:

`const drivelist = require('drivelist');`
 
`drivelist.list((error, drives) => {`
    `if (error) {`
      `throw error;`
    `}`
 
  `console.log(drives);`
`});`

I am using electron and it gives me this error when I try to run the program.
![error](https://user-images.githubusercontent.com/31454047/30921349-4e932ba6-a374-11e7-99dd-b5763e9cbff9.PNG)

I cannot give too much away about this code, but my initial idea was to have the user press a start button that would tell main.js to start scanning for devices but this error always shows. The code was working before using Electron so I'm guessing it's not supported or something but I would like to get an explanation for this. 

Thank you.

**Comment by danao-realityi** [comment]
Someone told me to look at this issue: https://github.com/electron/electron/issues/8466
and try `npm install electron --verbose` and now it's working. 
Not sure why though, but I am content.

**Comment by jhermsmeier** [comment]
Hey @danao-realityi, this happens when the module ABI (Application Binary Interface) differs between the installed module and the runtime – in this case the native bindings have been compiled against the Node version you've got, but then being run under Electron, which is why it can't find a suitable binding to load.

The reason why globally installing the latest version of Electron works in your case is just that the module ABIs happen to match, but this won't save you from this happening in the long run. Generally, I'd recommend installing Electron as a direct dependency of what you're building instead, and having a read through the [Using native node modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) doc in the Electron repository.

**Comment by danao-realityi** [comment]
I was looking at that native node modules documentation before and I kept getting errors in the command line. Initially I did have Electron installed as a dev dependency before testing the drivelist code, so I got that part right at least. But the errors I mentioned before were hard for me to decipher. I'm not sure how to recreate the error again. I even installed both electron-prebuilt and electron-rebuild to fix my issue. Maybe I was too quick to find a solution that I skimmed over the "using npm" part.

Thanks for explaining @jhermsmeier

**Comment by danao-realityi** [comment]
So I created a new program that simply starts with "electron ." with only these dependencies:
` "devDependencies": {
    "electron": "1.7.8",
    "electron-rebuild": "^1.6.0"
  },
  "dependencies": {
    "drivelist": "^5.1.8"
  }`

I followed the [native node module instructions](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) and got this error.

![image](https://user-images.githubusercontent.com/31454047/30968160-62d5398e-a42c-11e7-92d7-9030632ed9f6.png)

I know this wasn't the same error as above, but I thought it would be appropriate to reopen this issue since following those instructions, didn't give me the desired result.
What causes certain node modules to require these extra instructions to work in Electron then other node modules?

**Comment by jhermsmeier** [comment]
Not sure what's going on there, but there are basically two ways of doing this, both of which work perfectly fine for me:

**Electron Rebuild:**

If you want to use electron-rebuild, stick the following in your package.json:

```json
"scripts": {
  "electron-rebuild": "electron-rebuild -f -s -v 1.7.8"
}
```

then install your desired dependencies:

```bash
npm install --save drivelist
```

then rebuild the dependencies against electron by running:

```bash
npm run electron-rebuild
```

**Manually:** 

Create a file `electron-build.sh`:

```bash
#!/usr/bin/env bash

# Electron's version
export npm_config_target=1.7.8
# The architecture of Electron, can be ia32 or x64
export npm_config_arch=x64
export npm_config_target_arch=x64
# Download headers for Electron
export npm_config_disturl=https://atom.io/download/electron
# Tell node-gyp that we are building for Electron
export npm_config_runtime=electron
# Tell node-gyp to build module from source
export npm_config_build_from_source=true

npm install --save "$1"
```

then run `./electron-install.sh drivelist` to install & build the dependency

**Comment by danao-realityi** [comment]
I followed the first instructions and they worked! :smile: 

Thank you so much @jhermsmeier
