### ISSUE TITLE
Include used/available storage numbers

### ISSUE THREAD

**Issue by sechastain** [resin-io-modules/drivelist#228]
Right now, it looks like only the raw bytes for a device is reported.

It would also be good to know how many bytes are in use and how many are unused.

**Comment by jhermsmeier** [comment]
Space usage on any given storage device is subject to the filesystems in the partitions, not the storage device itself. The device itself doesn't "know" how full / empty it is. There are several ways to determine space utilization on a storage device – but any of that is out of the scope of this module.

If you just want to know how much space partitions take up on a given device, you can read & parse the partition tables (this can be done with [node-mbr](https://github.com/jhermsmeier/node-mbr) and [node-gpt](https://github.com/jhermsmeier/node-gpt), for example). If you want to know how much "free" space the filesystems on each partition have, you'll need filesystem drivers for each one, and get that data from those.

**Comment by vasyl-shumskyi** [comment]
That's sad you not planing to implement this. I had to switch from drivelist to hdd-space because of this https://www.npmjs.com/package/hdd-space

**Comment by jhermsmeier** [comment]
Different tools for different jobs. This module is only concerned with detecting and listing available block devices on a system, not their partitions and volumes.

**Comment by vasyl-shumskyi** [comment]
Yep, I'm agree
