### ISSUE TITLE
Error on windows XP: The specified procedure could not be found 

### ISSUE THREAD

**Issue by GeethaG** [resin-io-modules/drivelist#233]
@jviotti : drivelist node module is throwing the error as it is in the attached screen shot
![drivelist](https://user-images.githubusercontent.com/15728031/32225235-6cf30a60-be6a-11e7-9b0f-b3c4edbb6471.png)

**Comment by GeethaG** [comment]
@jviotti - Could you please provide me some solution for windows XP

**Comment by lurch** [comment]
AFAIK `drivelist` was created for the purposes of Etcher. Etcher doesn't support WindowsXP, and so I think it unlikely that drivelist will be modified to support WindowsXP either.

(FWIW, Microsoft no longer supports WindowsXP either, and neither does NodeJS)

**Comment by jhermsmeier** [comment]
Which versions of node & npm are you using, and what are you running this in, nw.js?
Also, please keep in mind that Windows XP support was discontinued by Microsoft in 2009, and extended support in 2014 – if this is indeed an issue with `drivelist`, we won't be fixing it.

**Comment by GeethaG** [comment]
Hi @jhermsmeier , @lurch - Thank you for the quick response. I need to get the list of drives in the PC irrespective of OS. Some of the users of my application are using Windows XP as well. There are few other node modules which can fulfill my requirement but they are not working offline (without network). Drivelist is working without network after some modifications. is there any other solution for this?

**Comment by lurch** [comment]
If you **really** need to run on WindowsXP, maybe you'd have better luck with an old version v5.0.23 of drivelist which is the last version before we started re-implementing the Windows part in native C++ code? https://github.com/resin-io-modules/drivelist/commit/fd3f3b45513e9f0b611ab8374b7c6dc1936f7fa0

But bear in mind there's obviously been _lots_ of other bugfixes to drivelist since then, so we won't be "supporting" that ;-)

**Comment by GeethaG** [comment]
Tried to install the version specified and got the below error:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "drivelist@5.0.23"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: drivelist@5.0.23
npm ERR! notarget Valid install targets:
npm ERR! notarget 5.2.6, 5.2.5, 5.2.4, 5.2.3, 5.2.2, 5.2.1, 5.2.0, 5.1.8, 5.1.7, 5.1.6, 5.1.5, 5.1.4, 5.1.3, 5.1.2, 5.1.1, 5.1.0, 5.0.28, 5.0.27, 5.0.26, 5.0.25, 5.0.22, 5.0.21, 5.0.20, 5.0.19, 5.0.18, 5.0.17, 5.0.16, 5.0.15, 5.0.14, 5.0.1
3, 5.0.12, 5.0.11, 5.0.10, 5.0.9, 5.0.8, 5.0.7, 5.0.6, 5.0.5, 5.0.4, 5.0.3, 5.0.2, 5.0.1, 5.0.0, 4.0.0, 3.3.4, 3.3.3, 3.3.2, 3.3.1, 3.3.0, 3.2.6, 3.2.5, 3.2.4, 3.2.3, 3.2.2, 3.2.1, 3.2.0, 3.1.2, 3.1.1, 3.1.0, 3.0.0, 2.0.14, 2.0.13, 2.0.12,
 2.0.11, 2.0.10, 2.0.9, 2.0.8, 2.0.7, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.3.2, 1.3.1, 1.3.0, 1.2.2, 1.2.1, 1.2.0, 1.1.2, 1.1.1, 1.1.0, 1.0.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:

**Comment by lurch** [comment]
Ahh, I guess we didn't publish version 5.0.23 then. In which case you could try version 5.0.22 which _is_ included in your list of available versions?

**Comment by jhermsmeier** [comment]
> There are few other node modules which can fulfill my requirement but they are not working offline (without network). Drivelist is working without network after some modifications.

Can you explain what you mean by "not working offline (without network)"?
And what modifications do you need to make drivelist work?

**Comment by GeethaG** [comment]
Hi @jhermsmeier   Without Ethernet connection application is getting crashed. This is what I meant by above sentence. I have removed the code related to child_process. Please let me know if this clarifies

**Comment by jhermsmeier** [comment]
The [child_process] API doesn't have anything to do with the network either – is there some part of your application that relies on the network and doesn't handle errors (in the spawned child process itself possibly), causing it to crash?

[child_process]: https://nodejs.org/docs/v6.11.5/api/

**Comment by GeethaG** [comment]
Immediately after executing the 'require('child_process')' line of code, application is getting closed automatically. There is no dependency of network in my application.

**Comment by jhermsmeier** [comment]
That makes little sense to me, and with the limited information I have, I'm afraid I can't really help you. Keep in mind that support for Windows XP has been dropped in Node 6 (see https://github.com/nodejs/node/issues/3804) – so in case you're trying to run Node 6+, or a recent version of Electron or NW.js on Windows XP – that's probably not going to work.

**Comment by GeethaG** [comment]
@jhermsmeier  - Thank you for the information provided.
