### ISSUE TITLE
[Windows] Protected does not reflect READONLY attribute on disks

### ISSUE THREAD

**Issue by robinwassen** [resin-io-modules/drivelist#240]
**Reproduction environment:** Windows 10 1703

**Steps to reproduce:**
- Make a USB drive READONLY - [guide](http://www.getusb.info/how-to-make-a-usb-read-only/)
- Execute `drivelist.list(...)`
- Check the properties of the USB drive

**Expected result:** protected should be true

**Actual result:** protected is false

**Comment by jhermsmeier** [comment]
This should now be fixed since v6.0.0 – but note that a device that contains a volume that's marked readonly, but the device itself not being readonly will not show up with `.isReadOnly == true`.
Feel free to re-open this issue if there's still a problem with this.
