### ISSUE TITLE
6.0.1 fails in Mac OS

### ISSUE THREAD

**Issue by DirtyRed5789** [resin-io-modules/drivelist#247]
ERROR:  { Error: Command failed: bash /var/folders/dx/_9_rxzx519n57sjcz5wc5d2w0000gn/T/drivelist-1b10b864ac31.sh
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
 (code 1, signal none)
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'bash /var/folders/dx/_9_rxzx519n57sjcz5wc5d2w0000gn/T/drivelist-1b10b864ac31.sh' }
DRIVES:  undefined

**Comment by DirtyRed5789** [comment]
Node LTS 8.9.3
clean install with:

`const drivelist = require('drivelist');

        drivelist.list((error, drives) => {
            console.log('ERROR: ', error);
            console.log('DRIVES: ', drives);
        });
`

**Comment by lurch** [comment]
Yikes! Thanks for letting us know. See https://github.com/resin-io-modules/drivelist/pull/246

@jhermsmeier or @jviotti Do different versions of OSX have `sed` commands with different CLI flags? :-/
Technical details: I needed to use the `-r` flag to sed to enable the use of the `+` character in the regexes (just like the way `grep` also needs the `-E` flag to use the `+` regex character).

**Comment by lurch** [comment]
@DirtyRed5789 #248 should fix this :)

Turns out the `-r` flag is specific to GNU sed (which I guess is what @jhermsmeier must have been using in #246 ?)
https://unix.stackexchange.com/a/131940

**Comment by jhermsmeier** [comment]
Yup, I have the GNU sed installed :/
