### ISSUE TITLE
USB mountpoints is empty when I plugin usb flash driver in linux

### ISSUE THREAD

**Issue by mahdi-gh1373** [resin-io-modules/drivelist#251]
I have a odroid device and I install linux lxde on it.I have a lcd on it to work with my nodejs program.when i was login as root in to device via remote desktop the driverlist show drives and I can see usb mountpoint(I have one sd card and one usb drive) : 

```
[{
  "device": "/dev/sda",
  "displayName": "/dev/sda",
  "description": "Ultra Fit",
  "size": 15376000000,
  "mountpoints": [{
    "path": "/media/root/DISK"
  }],
  "raw": "/dev/sda",
  "protected": false,
  "system": false
}, {
  "device": "/dev/mmcblk0",
  "displayName": "/dev/mmcblk0",
  "description": "SL16G",
  "size": 15931539456,
  "mountpoints": [{
    "path": "/"
  }, {
    "path": "/media/boot"
  }],
  "raw": "/dev/mmcblk0",
  "protected": false,
  "system": false
}]
```

but If I didn't login via remote and odroid boot and automatically login I can't see mountpoint and it's empty!!!

```
[{
  "device": "/dev/sda",
  "displayName": "/dev/sda",
  "description": "Ultra Fit",
  "size": 15376000000,
  "mountpoints": [],
  "raw": "/dev/sda",
  "protected": false,
  "system": false
}, {
  "device": "/dev/mmcblk0",
  "displayName": "/dev/mmcblk0",
  "description": "SL16G",
  "size": 15931539456,
  "mountpoints": [{
    "path": "/"
  }, {
    "path": "/media/boot"
  }],
  "raw": "/dev/mmcblk0",
  "protected": false,
  "system": false
}]
```

**Comment by lurch** [comment]
In the second case, are you sure the drive is _actually_ mounted?

In the first case you say "login as root in to device via remote desktop" - quite often it'll be the remote desktop itself that actually mounts the USB drives to `/media/username/whatever`. If you want this to happen automatically (without running a desktop) you'd need to add an appropriate entry to `/etc/fstab`.

**Comment by mahdi-gh1373** [comment]
@lurch  Yes this problem was because of the remote desktop itself that actually mounts the USB drives to `/media/username/whatever ` so the answer is here : 
[https://unix.stackexchange.com/questions/44454/how-to-mount-removable-media-in-media-label-automatically-when-inserted-with](url)

 To summarize: create a udev rule, associated with some scripts (that will create/remove directories and un/mount removable devices), and attached to udev device event type=partition.

**1 - Creating add / remove scripts**

Save following script storage-automount.sh to /lib/udev/ and make it executable (sudo chmod a+x /lib/udev/storage-automount.sh):

```
#!/bin/sh

# set the mountpoint name according to partition or device name
mount_point=$ID_FS_LABEL
if [ -z $mount_point ]; then
    mount_point=${DEVNAME##*/}
fi

# if a plugdev group exist, retrieve it's gid set & it as owner of mountpoint
plugdev_gid="$(grep plugdev /etc/group|cut -f3 -d:)"
if [ -z $plugdev_gid ]; then
    gid=''
else
    chown root:plugdev $mount_point
    gid=",gid=$plugdev_gid"
fi

# create the mountpoint directory in /media/ (if not empty)
if [ -n $mount_point ]; then
    mkdir -p /media/$mount_point
    # other options (breaks POSIX): noatime,nodiratime,nosuid,nodev
    mount -t $ID_FS_TYPE \
      -o rw,flush,user,uid=0$gid,umask=002,dmask=002,fmask=002 \
      $DEVNAME /media/$mount_point
fi
```
Save following script storage-autounmount.sh to /lib/udev/ and make it executable (sudo chmod a+x /lib/udev/storage-autounmount.sh):

```
#!/bin/sh

# set the mountpoint name according to partition or device name
mount_point=$ID_FS_LABEL
if [ -z $mount_point ]; then
    mount_point=${DEVNAME##*/}
fi

# remove the mountpoint directory from /media/ (if not empty)
if [ -n $mount_point ]; then
    umount -l /media/$mount_point
    rm -R /media/$mount_point
fi

```
**2 - Creating the udev rule to attach those scripts to events**

And finally, add a udev rule in /etc/udev/rules.d/, for instance 85-storage-automount.rules:

`ENV{DEVTYPE}=="partition", RUN+="/lib/udev/storage-automount.sh", ENV{REMOVE_CMD}="/lib/udev/storage-autounmount.sh"`
and make it have the same permissions as the other rules in that dir/folder

Now, when you plug a storage device in, a directory will be created in /media/ according to the partition name (I don't remember but I think it's working with NTFS partition as well) and your partition will be mounted into it. It's R/W for users if you have a plugdev group on your system. Also, the devices are mounted in synchronous mode in order to limit the risks of data loss in case of hot unplugging.

When the device is removed, it's unmounted and the directory is removed from /media

Also, the tool to monitor the udev events is udevadm monitor, with options like --env or --property:

$ udevadm monitor --env
This is tested and working fine on both debian and arch, but probably work on all distributions that rely on udev.
