### ISSUE TITLE
npm install fails with `ENOENT: no such file or directory, chmod '.../node_modules/drivelist/scripts/darwin.sh'`

### ISSUE THREAD

**Issue by andrewmbenton** [resin-io-modules/drivelist#257]
This is perhaps specific to my machine, which is running GNU/Linux (Ubuntu), but seems like probably not. I'm using node v8.9.4 and npm v5.7.1.

Looks like https://github.com/resin-io-modules/drivelist/tree/master/scripts no longer includes this file?

**Comment by jhermsmeier** [comment]
Yup, that was a bug, fixed by #256 and published as `drivelist@6.1.1`

**Comment by andrewmbenton** [comment]
All good now, thanks.
