### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by lefuturiste** [resin-io-modules/drivelist#269]
Hi! 

I have a problem when I try to get the drive list:

`[Vue warn]: Error in mounted hook: "TypeError: Path must be a string. Received undefined"`

```
Path must be a string. Received undefined
    at assertPath (path.js:28)
    at dirname (path.js:716)
    at Function.getRoot (bindings.js?f3ff:151)
    at bindings (bindings.js?f3ff:60)
```

And I have warning, linked with that I think.

```
[HMR] bundle has 2 warnings
client.js?7955:189 ./node_modules/bindings/bindings.js
81:22-40 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/bindings/bindings.js
 @ ./src/drivelist/drivelist.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/components/Write.vue
 @ ./src/renderer/components/Write.vue
 @ ./src/renderer/router/index.js
 @ ./src/renderer/main.js
 @ multi ./.electron-vue/dev-client ./src/renderer/main.js
./node_modules/bindings/bindings.js
81:43-53 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/bindings/bindings.js
 @ ./src/drivelist/drivelist.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/components/Write.vue
 @ ./src/renderer/components/Write.vue
 @ ./src/renderer/router/index.js
 @ ./src/renderer/main.js
 @ multi ./.electron-vue/dev-client ./src/renderer/main.js
```

I'm on Windows 10 to build a Electron desktop app, working with Webpack, NodeJS, Vue Js.

Thanks for your anwser !

**Comment by lurch** [comment]
Looks like this might be the same as #210 ?

**Comment by jhermsmeier** [comment]
This is due to being bundled (by webpack?) – this module makes use of native bindings, and "Critical dependency: the request of a dependency is an expression" hints at that it can't resolve the path to the native binding due to the lack of a value, which in turn is probably not shimmed by the bundler, or not available in that context (missing `__dirname` and/or `__filename`?)

**Comment by lefuturiste** [comment]
How I can fix that ?

**Comment by jhermsmeier** [comment]
I'm afraid I can't help you with that; but this doesn't appear to be an issue with `drivelist`

**Comment by erikjalevik** [comment]
I had the same error but managed to work around it by adding the following to my webpack config:

```
module.exports = {
  externals: {
    drivelist: 'require("drivelist")'
  }
}
```
