### ISSUE TITLE
SD Card is not removable UBUNTU 18.04

### ISSUE THREAD

**Issue by amdomanska** [resin-io-modules/drivelist#303]
System: Ubuntu 18.04

When trying to flash os img to my sb card with Etcher, I've got SD card inserted and my system sees that but Etcher claims that "no removable drive detected".

running example/ gives an output:

```
[ { enumerator: 'lsblk:json',
    busType: 'SATA',
    busVersion: null,
    device: '/dev/sda',
    devicePath: 'pci-0000:00:17.0-ata-2',
    raw: '/dev/sda',
    description: 'ATA SanDisk X600 2.5 (ESP, OS, UBUNTU, [SWAP])',
    error: null,
    size: 512110190592,
    blockSize: 512,
    logicalBlockSize: 512,
    mountpoints: 
     [ { path: '/boot/efi', label: 'ESP' },
       { path: '/', label: 'UBUNTU' },
       { path: '[SWAP]', label: null } ],
    isReadOnly: false,
    isSystem: true,
    isVirtual: false,
    isRemovable: false,
    isCard: null,
    isSCSI: true,
    isUSB: false,
    isUAS: null },
  { enumerator: 'lsblk:json',
    busType: 'UNKNOWN',
    busVersion: null,
    device: '/dev/mmcblk0',
    devicePath: 'pci-0000:03:00.0-platform-rtsx_pci_sdmmc.0',
    raw: '/dev/mmcblk0',
    description: '(resin-boot, resin-rootA, resin-rootB, resin-state, resin-data)',
    error: null,
    size: 31914983424,
    blockSize: 512,
    logicalBlockSize: 512,
    mountpoints: [],
    isReadOnly: false,
    isSystem: true,
    isVirtual: false,
    isRemovable: false,
    isCard: null,
    isSCSI: null,
    isUSB: null,
    isUAS: null } ]
```
lsblk output:

```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0         7:0    0   2.3M  1 loop /snap/gnome-calculator/199
loop1         7:1    0 140.9M  1 loop /snap/gnome-3-26-1604/70
loop2         7:2    0  14.5M  1 loop /snap/gnome-logs/40
loop3         7:3    0  34.7M  1 loop /snap/gtk-common-themes/319
loop4         7:4    0  87.9M  1 loop /snap/core/5328
loop5         7:5    0   3.7M  1 loop /snap/gnome-system-monitor/54
loop6         7:6    0    13M  1 loop /snap/gnome-characters/117
sda           8:0    0   477G  0 disk 
├─sda1        8:1    0   800M  0 part /boot/efi
├─sda2        8:2    0     5G  0 part 
├─sda3        8:3    0 439.5G  0 part /
└─sda4        8:4    0  31.7G  0 part [SWAP]
mmcblk0     179:0    0  29.7G  0 disk 
├─mmcblk0p1 179:1    0    40M  0 part 
├─mmcblk0p2 179:2    0   312M  0 part 
├─mmcblk0p3 179:3    0   312M  0 part 
├─mmcblk0p4 179:4    0     1K  0 part 
├─mmcblk0p5 179:5    0    20M  0 part 
└─mmcblk0p6 179:6    0     1G  0 part 
```

**Comment by jhermsmeier** [comment]
Can you also post the output of `lsblk --bytes --paths --json --output-all`?

**Comment by amdomanska** [comment]
{
   "blockdevices": [
      {"name": "/dev/loop0", "kname": "/dev/loop0", "maj:min": "7:0", "fstype": "squashfs", "mountpoint": "/snap/gnome-calculator/199", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "2433024", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop1", "kname": "/dev/loop1", "maj:min": "7:1", "fstype": "squashfs", "mountpoint": "/snap/gnome-3-26-1604/70", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "147722240", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop2", "kname": "/dev/loop2", "maj:min": "7:2", "fstype": "squashfs", "mountpoint": "/snap/gnome-logs/40", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "15196160", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop3", "kname": "/dev/loop3", "maj:min": "7:3", "fstype": "squashfs", "mountpoint": "/snap/gtk-common-themes/319", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "36323328", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop4", "kname": "/dev/loop4", "maj:min": "7:4", "fstype": "squashfs", "mountpoint": "/snap/core/5328", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "92164096", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop5", "kname": "/dev/loop5", "maj:min": "7:5", "fstype": "squashfs", "mountpoint": "/snap/gnome-system-monitor/54", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "3887104", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/loop6", "kname": "/dev/loop6", "maj:min": "7:6", "fstype": "squashfs", "mountpoint": "/snap/gnome-characters/117", "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "1", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "13619200", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "1", "sched": "none", "rq-size": "128", "type": "loop", "disc-aln": "0", "disc-gran": "4096", "disc-max": "4294966784", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block", "rev": null, "vendor": null, "zoned": "none"},
      {"name": "/dev/sda", "kname": "/dev/sda", "maj:min": "8:0", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": "SanDisk X600 2.5", "serial": "182652800188", "size": "512110190592", "state": "running", "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "disk", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x5001b448b62cd5ff", "rand": "0", "pkname": null, "hctl": "1:0:0:0", "tran": "sata", "subsystems": "block:scsi:pci", "rev": "4012", "vendor": "ATA     ", "zoned": "none",
         "children": [
            {"name": "/dev/sda1", "kname": "/dev/sda1", "maj:min": "8:1", "fstype": "vfat", "mountpoint": "/boot/efi", "label": "ESP", "uuid": "F28F-55BD", "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b", "partlabel": "EFI system partition", "partuuid": "ca359edb-2f00-48d7-bb45-8255c5a19c66", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "838860800", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x5001b448b62cd5ff", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/sda2", "kname": "/dev/sda2", "maj:min": "8:2", "fstype": "vfat", "mountpoint": null, "label": "OS", "uuid": "24C0-9A15", "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7", "partlabel": "Basic data partition", "partuuid": "6dc09a4e-55ec-4ff7-bbb8-e303025ca271", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "5368709120", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x5001b448b62cd5ff", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/sda3", "kname": "/dev/sda3", "maj:min": "8:3", "fstype": "ext4", "mountpoint": "/", "label": "UBUNTU", "uuid": "98d377c4-4ed5-441b-84bb-49cf6a4287c3", "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4", "partlabel": null, "partuuid": "29e9b754-2dba-4cd8-85f6-0a70acd52c3d", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "471852908544", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x5001b448b62cd5ff", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/sda4", "kname": "/dev/sda4", "maj:min": "8:4", "fstype": "swap", "mountpoint": "[SWAP]", "label": null, "uuid": "f8ff4a79-57e7-423b-b31d-66a02451bb2d", "parttype": "0657fd6d-a4ab-43c4-84e5-0933c84b4f4f", "partlabel": null, "partuuid": "58b99ec4-3b4b-4453-a2e3-eb970124406d", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "0", "model": null, "serial": null, "size": "34048311296", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "512", "disc-max": "2147450880", "disc-zero": "0", "wsame": "0", "wwn": "0x5001b448b62cd5ff", "rand": "0", "pkname": "/dev/sda", "hctl": null, "tran": null, "subsystems": "block:scsi:pci", "rev": null, "vendor": null, "zoned": "none"}
         ]
      },
      {"name": "/dev/mmcblk0", "kname": "/dev/mmcblk0", "maj:min": "179:0", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": null, "partlabel": null, "partuuid": null, "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "1", "model": null, "serial": "0x187041f2", "size": "31914983424", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "disk", "disc-aln": "0", "disc-gran": "4194304", "disc-max": "3741319168", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": null, "hctl": null, "tran": null, "subsystems": "block:mmc:mmc_host:platform:pci", "rev": null, "vendor": null, "zoned": "none",
         "children": [
            {"name": "/dev/mmcblk0p1", "kname": "/dev/mmcblk0p1", "maj:min": "179:1", "fstype": "vfat", "mountpoint": null, "label": "resin-boot", "uuid": "05A2-BA22", "parttype": "0xe", "partlabel": null, "partuuid": "bb45572c-01", "partflags": "0x80", "ra": "128", "ro": "0", "rm": "0", "hotplug": "1", "model": null, "serial": null, "size": "41943040", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "4194304", "disc-max": "3741319168", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": "/dev/mmcblk0", "hctl": null, "tran": null, "subsystems": "block:mmc:mmc_host:platform:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/mmcblk0p2", "kname": "/dev/mmcblk0p2", "maj:min": "179:2", "fstype": "ext4", "mountpoint": null, "label": "resin-rootA", "uuid": "be236a54-b24e-466c-a841-27fb37c36f51", "parttype": "0x83", "partlabel": null, "partuuid": "bb45572c-02", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "1", "model": null, "serial": null, "size": "327155712", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "4194304", "disc-max": "3741319168", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": "/dev/mmcblk0", "hctl": null, "tran": null, "subsystems": "block:mmc:mmc_host:platform:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/mmcblk0p3", "kname": "/dev/mmcblk0p3", "maj:min": "179:3", "fstype": "ext4", "mountpoint": null, "label": "resin-rootB", "uuid": "5a558bda-0e2b-4bdc-bb60-3756944549aa", "parttype": "0x83", "partlabel": null, "partuuid": "bb45572c-03", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "1", "model": null, "serial": null, "size": "327155712", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "4194304", "disc-max": "3741319168", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": "/dev/mmcblk0", "hctl": null, "tran": null, "subsystems": "block:mmc:mmc_host:platform:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/mmcblk0p4", "kname": "/dev/mmcblk0p4", "maj:min": "179:4", "fstype": null, "mountpoint": null, "label": null, "uuid": null, "parttype": "0xf", "partlabel": null, "partuuid": "bb45572c-04", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "1", "model": null, "serial": null, "size": "1024", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "4194304", "disc-max": "3741319168", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": "/dev/mmcblk0", "hctl": null, "tran": null, "subsystems": "block:mmc:mmc_host:platform:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/mmcblk0p5", "kname": "/dev/mmcblk0p5", "maj:min": "179:5", "fstype": "ext4", "mountpoint": null, "label": "resin-state", "uuid": "89287ed0-cbcc-46b5-8c69-3c0df9f85e9c", "parttype": "0x83", "partlabel": null, "partuuid": "bb45572c-05", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "1", "model": null, "serial": null, "size": "20971520", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "4194304", "disc-max": "3741319168", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": "/dev/mmcblk0", "hctl": null, "tran": null, "subsystems": "block:mmc:mmc_host:platform:pci", "rev": null, "vendor": null, "zoned": "none"},
            {"name": "/dev/mmcblk0p6", "kname": "/dev/mmcblk0p6", "maj:min": "179:6", "fstype": "ext4", "mountpoint": null, "label": "resin-data", "uuid": "a05b0c89-a7f1-441a-bc24-bf262e92ade8", "parttype": "0x83", "partlabel": null, "partuuid": "bb45572c-06", "partflags": null, "ra": "128", "ro": "0", "rm": "0", "hotplug": "1", "model": null, "serial": null, "size": "1077936128", "state": null, "owner": "root", "group": "disk", "mode": "brw-rw----", "alignment": "0", "min-io": "512", "opt-io": "0", "phy-sec": "512", "log-sec": "512", "rota": "0", "sched": "cfq", "rq-size": "128", "type": "part", "disc-aln": "0", "disc-gran": "4194304", "disc-max": "3741319168", "disc-zero": "0", "wsame": "0", "wwn": null, "rand": "0", "pkname": "/dev/mmcblk0", "hctl": null, "tran": null, "subsystems": "block:mmc:mmc_host:platform:pci", "rev": null, "vendor": null, "zoned": "none"}
         ]
      }
   ]
}

**Comment by jhermsmeier** [comment]
Interesting, looks like `hotplug` property is new, or we previously missed it
