### ISSUE TITLE
network drives?

### ISSUE THREAD

**Issue by gbaumgart** [resin-io-modules/drivelist#56]
hi,
nice lib but what about network drives? Any pointer how to add this?
thank you

**Comment by jviotti** [comment]
Interesting feature. What OS are you running?

If you're running an UNIX based OS, are the network drives being registered as `/dev/` devices?

**Comment by gbaumgart** [comment]
I will need only for mac & windows then. I am trying to build custom file picker with it. Any glue where to go for windows? I think there are windows CLI commands to get a list of the mapped drives.

**Comment by gbaumgart** [comment]
yeah, parsing 'net use' will do for me, and for linux 'df -h' seems ok too, (i dont need the stats). now I just need to figure it for mac and done ;-)

**Comment by gbaumgart** [comment]
ah, df -h works on mac too. For me its done, i will implement this in my fork but I doubt I will make a PR since i will remove coffee script as well.
