### ISSUE TITLE
Win32 Physical Drive 0 always reports system property as being true

### ISSUE THREAD

**Issue by userabuser** [resin-io-modules/drivelist#61]
`Win32.bat` will always report `\\.\PHYSICALDRIVE0` as being system drive when in actual fact system drive can exist on any physical drive of one's choosing.

As in my case, `\\.\PHYSICALDRIVE1` is the system drive.

```javascript
//drive 1
description: "OCZ-VERTEX3 ATA Device"
device: "\\.\PHYSICALDRIVE1"
mountpoint: "C:"
name: "C:"
size: "120 GB"
system: false //should be true

//drive 2
description: "WDC WD5000AAKS-00YGA0 ATA Device"
device: "\\.\PHYSICALDRIVE0"
mountpoint: "D:"
name: "D:"
size: "500 GB"
system: true  //should be false
```

The only reliable way that I can tell to determine the system drive is to query against `Win32_OperatingSystem` for the `SystemDrive` property.

```vbs
Private OSDrive

Set colOperatingSystems = objWMIService.ExecQuery ("SELECT SystemDrive FROM Win32_OperatingSystem")

For Each objOperatingSystem in colOperatingSystems
    On Error Resume Next
    '' get the OS System Drive if exists
    OSDrive = objOperatingSystem.Properties_("SystemDrive")   
    If Err.Number <> 0 Then
        OSDrive = Err.Description
        Err.Clear
    End If
Next
```

The result of which is stored against the variable `OSDrive` for which we can later compare against...

```vbs
If objLogicalDisk.DeviceID = OSDrive Then
  Wscript.Echo "system: True"
Else
  Wscript.Echo "system: False"
End If
```
This results in the correct drive attaining `(bool) true` for the `system` property returned by `drivelist.list()` 

Related PR for this issue:
#60

**Comment by jviotti** [comment]
Very cool! We overlooked this fact after experimenting with some PCs and noticing that system drive was always `\\.\PHYSICALDRIVE0`. I'll review and test your PR in a minute. Thanks a lot!
