### ISSUE TITLE
does not find mountpoint for disk mounted by UUID

### ISSUE THREAD

**Issue by squirrelpiles** [resin-io-modules/drivelist#68]
on Ubuntu (and probably all other Linux), drives mounted by UUID like this line from /etc/fstab:
     
UUID=7af69416-051a-4149-a3e8-9b59becb56f7 /               ext4    errors=remount-ro 0       1

do not return a mountpoint using this module.   The entry in /procs/mounts for such a disk looks like this:

/dev/disk/by-uuid/7af69416-051a-4149-a3e8-9b59becb56f7 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0

so the code that greps for the the device fails.

**Comment by jviotti** [comment]
I see. I can think of the following solution:

- If the mount point is not detected by greping `/proc/mounts` with the device path, get the UUID of such device and try finding it in `/proc/mounts` that way.

I'll implement this and we'll see how it works.

**Comment by jviotti** [comment]
Hi @squirrelpiles ,

I implemented a fix here: https://github.com/resin-io-modules/drivelist/pull/70. Do you mind checking out the PR and confirm it works for you?

**Comment by squirrelpiles** [comment]
Thank you.   This is good.  If you are satisfied with this, can you update the package on npm? 

here is output of calling linux.sh directly:
device: /dev/sda
description: Hitachi HDT72101
size: 931.5G
mountpoint: /,/var/lib/docker/aufs,
name: /dev/sda
system: True

device: /dev/sdf
description: Expansion Desk  
size: 4.6T
mountpoint: /media/dave/Seagate\040Expansion\040Drive,
name: /dev/sdf
system: False

device: /dev/sdg
description: 5000AAK External
size: 465.8G
mountpoint: /media/dave/500GUSB,
name: /dev/sdg
system: False

device: /dev/sdh
description: My Passport 0730
size: 931.5G
mountpoint: /media/dave/1T_External,
name: /dev/sdh
system: False

device: /dev/sdi
description: USB DISK 20X    
size: 962M
mountpoint: 
name: /dev/sdi
system: False

device: /dev/sdj
description: Storage Media   
size: 1.9G
mountpoint: /media/dave/C4B5-47E8,
name: /dev/sdj
system: False

**Comment by jviotti** [comment]
@squirrelpiles Perfect, I'll merge and publish in a second.

**Comment by jviotti** [comment]
@squirrelpiles I published v2.0.14 to NPM.
