### ISSUE TITLE
[Windows] Show drives without any Windows partitions

### ISSUE THREAD

**Issue by peakwinter** [resin-io-modules/drivelist#72]
Presently on Windows, this module only shows drives that have Windows mountable partitions (i.e. drives that show up with drive letters after `Win32_LogicalDiskToPartition`). Empty removable drives, or removable drives that only have HFS or ext partitions, will not show up. Is this intended behaviour or just an oversight? If the latter I would be happy to submit a pull request to fix...

Thanks!

**Comment by jviotti** [comment]
Hi @peakwinter ,

If there is a way to make them visible, happy to take a PR :)

**Comment by peakwinter** [comment]
I have a commit in a local branch that works and am ready to send a pull -- a question first though, what should be the value of the `name` property in these cases? If it's not a mountable drive, it will have a device ID (like `\\.\PHYSICALDRIVE1`) but not a drive letter, of course. Name could also be set to `null` but that seems a bit fishy to me. And would likely require a change to what is displayed for `name` in all cases...

**Comment by jviotti** [comment]
Hi @peakwinter ,

Sounds exciting, looking forward to give it a go! :)

Regarding `name`, it already defaults to `null` when the drive doesn't have a drive letter attached to it, so `null` should be good to go :+1:

**Comment by jviotti** [comment]
Thanks a lot @peakwinter! I published v3.1.0 to NPM with your addition.

**Comment by peakwinter** [comment]
No prob, thanks for the great module :)
