### ISSUE TITLE
Description on El Capitain

### ISSUE THREAD

**Issue by eemi2010** [resin-io-modules/drivelist#88]
I m getting WDC WD5000LPVX-22V0TT0 for the description instead of a readable name. What I m  I doing wrong.

**Comment by jviotti** [comment]
Hi @eemi2010 ,

We only display what the OS detects to be the description. Can you show us the output of `diskutil info /dev/diskN`, where N corresponds to your drive id, to see if we can find such information from other place?

**Comment by eemi2010** [comment]
Hey there. This is what  I get when  I run diskutil info /dev/disk1. Hope it can help.

Device Identifier:        disk1
   Device Node:              /dev/disk1
   Whole:                    Yes
   Part of Whole:            disk1
   Device / Media Name:      WDC WD5000LPVX-22V0TT0

   Volume Name:              Macintosh HD

   Mounted:                  Yes
   Mount Point:              /

   File System Personality:  Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Journaled)
   Journal:                  Journal size 40960 KB at offset 0x15be5000
   Owners:                   Enabled

   Content (IOContent):      Apple_HFS
   OS Can Be Installed:      Yes
   Recovery Disk:            disk0s3
   Media Type:               Generic
   Protocol:                 SATA
   SMART Status:             Not Supported
   Volume UUID:              611FF4C1-1528-35A1-B45F-11C80D8A852D
   Disk / Partition UUID:    E9BADD4A-BCED-4B1F-B7BC-AB534B049BB2

   Total Size:               498.9 GB (498876809216 Bytes) (exactly 974368768 512-Byte-Units)
   Volume Free Space:        129.9 GB (129917546496 Bytes) (exactly 253745208 512-Byte-Units)
   Device Block Size:        512 Bytes
   Allocation Block Size:    4096 Bytes

   Read-Only Media:          No
   Read-Only Volume:         No

   Device Location:          Internal
   Removable Media:          No

   Solid State:              No
   Virtual:                  Yes
   OS 9 Drivers:             No
   Low Level Format:         Not supp

**Comment by jviotti** [comment]
Hey there!

What you see is indeed what the OS reports as the drive name:

```
Device / Media Name:      WDC WD5000LPVX-22V0TT0
```

Can you provide an example of the string you were expecting instead?

**Comment by eemi2010** [comment]
Hi, 

I was expecting it to be "Macintosh HD" since that s what I see on my explorer. Wondering if I m the only one having this issue

**Comment by jviotti** [comment]
Hi @eemi2010 ,

I see, we could use `Volume Name` in case it exists. I'll send a PR very soon.

**Comment by jviotti** [comment]
I'm happy to announce I've released v3.3.0, which will show the nice readable volume name if it exists! Let me know if you still encounter the issue!
