### ISSUE TITLE
Does not list empty DVD drives on Windows

### ISSUE THREAD

**Issue by Eugeny** [resin-io-modules/drivelist#96]

**Comment by jviotti** [comment]
Hi @Eugeny ,

If there is no DVD inserted in your drive, then this is the expected behavior, since there is no volume mounted in the system.

**Comment by Eugeny** [comment]
Well, that makes sense, thanks for the info. That would make a nice feature though, because it's otherwise impossible to pick a free drive letter using this library.

For everyone else who stumble upon this, fs.readdirSync raises ENOENT for free drive letters and an undefined error for empty DVD drives.
