### ISSUE TITLE
Drive name inconsistencies on MacOSx

### ISSUE THREAD

**Issue by Dayjo** [resin-io-modules/drivelist#97]
Hello,

There seem to be some inconsistencies with what is returned as the `description`. Unsure if this is related to OS (Mac OSX) or the format of the drives, but what is output in Finder, is not what is returned as the description in drivelist.

For instance, the 'name' of the following drive is "DAYJOS USB" or at least this is what is shown up on Finder.

``` js
{
     device: '/dev/disk2',
     description: 'Flash Disk',
     size: 501219328,
     mountpoint: '/Volumes/DAYJOS USB',
     name: '/dev/disk2',
     raw: '/dev/rdisk2',
     protected: false,
     system: true
}
```

However this is what is found by diskutil;

```
Device Identifier:        disk2s1
   Device Node:              /dev/disk2s1
   Whole:                    No
   Part of Whole:            disk2
   Device / Media Name:      Untitled 1

   Volume Name:              DAYJOS USB

   Mounted:                  Yes
   Mount Point:              /Volumes/DAYJOS USB

   File System Personality:  MS-DOS FAT16
   Type (Bundle):            msdos
   Name (User Visible):      MS-DOS (FAT16)

   Partition Type:           DOS_FAT_16
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 USB
   SMART Status:             Not Supported
   Volume UUID:              2532FA31-46B3-3FEA-B37F-9D958B64CB67

   Total Size:               501.2 MB (501170176 Bytes) (exactly 978848 512-Byte-Units)
   Volume Free Space:        471.5 MB (471506944 Bytes) (exactly 920912 512-Byte-Units)
   Device Block Size:        512 Bytes
   Allocation Block Size:    8192 Bytes

   Read-Only Media:          No
   Read-Only Volume:         No

   Device Location:          External
   Removable Media:          No
```

As you can see there seems to be some issues with what Diskutil is returning, i.e.Removable Media: No, for instance must be incorrect, another external USB drive appears like so;

```

   Device Identifier:        disk1s1
   Device Node:              /dev/disk1s1
   Whole:                    No
   Part of Whole:            disk1
   Device / Media Name:      Untitled 1

   Volume Name:              USB Disk

   Mounted:                  Yes
   Mount Point:              /Volumes/USB Disk

   File System Personality:  MS-DOS FAT32
   Type (Bundle):            msdos
   Name (User Visible):      MS-DOS (FAT32)

   Partition Type:           Windows_FAT_32
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 USB
   SMART Status:             Not Supported
   Volume UUID:              0AF86554-9EB1-3535-89E2-4F930292CBE3

   Total Size:               15.7 GB (15703457792 Bytes) (exactly 30670816 512-Byte-Units)
   Volume Free Space:        14.7 GB (14689353728 Bytes) (exactly 28690144 512-Byte-Units)
   Device Block Size:        512 Bytes
   Allocation Block Size:    8192 Bytes

   Read-Only Media:          No
   Read-Only Volume:         No

   Device Location:          External
   Removable Media:          Yes
   Media Removal:            Software-Activated
```

However at least on mac, on these USB disks, 'Volume Name' seems to be a valid value to use as the name/description within drivelist. 

This second drive above appears like so in drivelist;

``` js
{ 
    device: '/dev/disk1',
     description: 'USB Flash Drive',
     size: 15703474176,
     mountpoint: '/Volumes/USB Disk',
     name: '/dev/disk1',
     raw: '/dev/rdisk1',
     protected: false,
     system: false
}
```

As you can see, the description is "USB Flash Drive" but the 'name' (the end of the mount point" is "USB Disk" as per the diskutil's 'Volume Name'.

If there's any more info I can get, please let me know :)

**Comment by jviotti** [comment]
Thank you very much for the detailed report! I'll be investigating shortly!

**Comment by jviotti** [comment]
In the first example, the disk name, as a whole, is "Flash disk". "DAYJOS USB" is label of one its partitions. Drivelist scans top level drives, which is the reason it doesn't consider partition labels.

Regarding the fact that the first one is detected as a system drive, there not much we can do in that case. For some reason OS X thinks is not removable, and we depend on the operating system to be able to detect that. 

I suggest you to investigate if you can tweak OS X to see your drive as removable, or in case its an SDCard or something, use another reader, or something like that.
