### ISSUE TITLE
Improve "mountpoint" contents

### ISSUE THREAD

**Issue by feliupe** [resin-io-modules/drivelist#98]
Hi guys,

I am using Kubuntu and I am having a problem to get the my mountpoints, I am having just one value in the 'disks' array, having the 'mountpoint' value equal '/,/usr'. Maybe the right output should be something like: 

disks = [{mountpoint: '/', ...}, {mountpoint: '/usr', ...}]

Tell me if I can help with something. Thx

**Comment by jviotti** [comment]
Hi @feliupe,

The purpose of `drivelist` is to list "top-level" disks (e.g: `/dev/sda`, `/dev/sdb`) rather than partitions, which is the reason a single top level disk may contain multiple partitions.

Ideally, we could make each drive contain a `partitions` property each including a different mount-point, but again, this is not the main purpose of `drivelist` and therefore not something we are prioritizing work for.

That being said, happy to take a PR of the improvement discussed above!

**Comment by feliupe** [comment]
Thanks for your response @jviotti. I will consider about it. I've been taking a look on this part of the code and seems to not be that complex.

I will try to manage my time to work on it, but not sure. In this case should the issue be close?

**Comment by jviotti** [comment]
Sounds great! Don't hesitate in pinging me if I can help with anything. Notice that the PR should implement this feature for all supported platforms. Happy to help/test on any platform you don't have access to.

Let's keep the issue opened until it gets implemented.

**Comment by lurch** [comment]
I've just been wondering a very similar question (but from a slightly different viewpoint): instead of `mountpoint` being a single comma-separated string, would it be better for mountpoint to instead return a list of strings? Might even make sense to rename it to `mountpoints` in that case. E.g. `mountpoints: ['/', '/usr'],` ?  (which would also accommodate the highly-unlikely situation of a mountpoint itself containing a comma, which wouldn't work properly with the current code)

Obviously that breaks backwards-compatibility though, so would necessitate a version jump to 5.0.0

**Comment by lurch** [comment]
In https://github.com/resin-io-modules/drivelist/issues/85#issuecomment-257383810 @jviotti said:
> Since changing the format of mountpoint is a breaking change, I suggest starting with the following:
```
[
  {
    "device": "/dev/sda",
    "mountpoints": [
      {
        "path": "/dev/sda1"
      },
      {
        "path": "/dev/sda2"
      }
    ],
    ...
  }
]
```

IMHO `path` is too Unix-centric (it implies a filesystem-path). That's why I [suggested](https://github.com/resin-io-modules/drivelist/issues/85#issuecomment-257266924) `partition` instead ;-)

....oh! I see now that you're suggesting using an array of dictionaries, instead of just a dictionary of dictionaries. Does that offer any advantages?

**Comment by jviotti** [comment]
> IMHO path is too Unix-centric (it implies a filesystem-path). That's why I suggested partition instead ;-)

In the case of Windows, `path` will include a drive letter, like `D:`. I find `partition: 'D:'` to look a bit weird, and I've seen Windows refer to `path` in various parts of its own documentation (see https://technet.microsoft.com/en-us/library/cc753321(v=ws.11).aspx for example).

> ....oh! I see now that you're suggesting using an array of dictionaries, instead of just a dictionary of dictionaries. Does that offer any advantages?

An array of dictionaries is simpler to iterate than a dictionary of dictionaries, and has the benefit that the whole information is contained in a single dictionary, while in the dictionary of dictionaries, the "path" is the actual key, but its not included in the dictionary itself.

**Comment by jviotti** [comment]
I've sent a PR organizing `mountpoints` as an array of objects which will close this issue. Once that is merged, we can discuss extending the object with more useful information, such as the partition device path, maybe partition size, etc.

**Comment by lurch** [comment]
> > IMHO path is too Unix-centric (it implies a filesystem-path). That's why I suggested partition instead

> In the case of Windows, path will include a drive letter, like D:. I find partition: 'D:' to look a bit weird

Ah, I think I see what's going on now, I guess your earlier example **should** have been:
```
[
  {
    "device": "/dev/sda",
    "mountpoints": [
      {
        "path": "/"
      },
      {
        "path": "/usr"
      }
    ],
    ...
  }
]
```
in which case `path` does indeed make sense.

> An array of dictionaries is simpler to iterate than a dictionary of dictionaries, and has the benefit that the whole information is contained in a single dictionary, while in the dictionary of dictionaries, the "path" is the actual key, but its not included in the dictionary itself.

Fair enough. I guess I'm more used to how things are done in the Python world (where there's a big emphasis on DRY), than how things are done in the JavaScript world ;-)

**Comment by jviotti** [comment]
Oh yeah, my bad, sorry for that! 

> Fair enough. I guess I'm more used to how things are done in the Python world (where there's a big emphasis on DRY), than how things are done in the JavaScript world ;-)

Imagine that you want to save a specific "mount point" from `drivelist` as a variable:

```js
const mountpoint = drives[0].mountpoints['/usr'];
```

You saved the mount point information, excluding the actual path, to a variable. If you need the actual path, then it means we have to extend the variable manually:

```js
const mountpoint = drives[0].mountpoints['/usr'];
mountpoint.path = '/usr';
```

Which is definitely not DRY. We can always duplicate the path in the dictionary itself, but that wouldn't be DRY neither:

```js
[
  {
    "device": "/dev/sda",
    "mountpoints": {
      "/usr": {
        "path": "/usr"
      }      
    ],
    ...
  }
]
```

I'm not saying that a dictionary of dictionaries is bad (it feels very natural indeed), but might not be very convenient to manipulate in certain scenarios.

**Comment by lurch** [comment]
Fair enough, it obviously depends on your perceived usage scenarios ;-)  And for the etcher project, you have a _much_ better handle on that than I do!

Just for the sake of devil's-advocate, a dictionary-of-dictionaries makes it easier to e.g. get the `size` of the partition mounted at e.g. `/usr` than a list-of-dictionaries would. But you can't please all of the people all of the time, because some people might want to get the size of a specific partition, rather than the size of a specific mountpoint.

**Comment by Fordi** [comment]
In POSIX systems, a particular partition may be mounted at multiple points.  If we're representing things using a separate `mountpoints` object, it should be a partition-centric object, e.g., 

	[
	  {
		"device": "/dev/sda",
		"mountpoints": {
                   /* "partition node": [ "mount path 1", "mount path 2", ... ],
		  "/dev/sda1": [ "/"  ],
                  "/dev/sda2": [ "/home", "/media/sda2" ]
		],
                ...
	  }
	]

**Comment by lurch** [comment]
> In some POSIX systems, a particular partition may be mounted at multiple paths

Oh? Can you provide some references / examples?
I tried googling for such a thing, and the only thing I found were 'bind mounts' where you're mounting an existing directory path to another directory path, not where you're mounting the same partition to two separate mount points.

**Comment by Fordi** [comment]
Sure.  Here's the content of /proc/mounts on my system (note: I have not manually configured anything here):

	sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
	proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
	udev /dev devtmpfs rw,nosuid,relatime,size=7843352k,nr_inodes=1960838,mode=755 0 0
	devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
	tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1572916k,mode=755 0 0
	none /dev/.bootchart/proc proc rw,relatime 0 0
	/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
	tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
	tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
	tmpfs /sys/fs/cgroup tmpfs rw,mode=755 0 0
	cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
	cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb 0 0
	cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids 0 0
	cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
	cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event 0 0
	cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
	systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
	mqueue /dev/mqueue mqueue rw,relatime 0 0
	hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
	debugfs /sys/kernel/debug debugfs rw,relatime 0 0
	sunrpc /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
	fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
	/dev/sdb1 /home ext4 rw,relatime,data=ordered 0 0
	binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
	cgmfs /run/cgmanager/fs tmpfs rw,relatime,size=100k,mode=755 0 0
	/usr/local/bin/autosshfs-map /home/rsi-bryan/mnt/ssh autofs rw,relatime,fd=6,pgrp=2373,timeout=600,minproto=5,maxproto=5,indirect 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33 ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	proc /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/proc proc rw,nosuid,nodev,noexec,relatime 0 0
	sysfs /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
	udev /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/dev devtmpfs rw,nosuid,relatime,size=7843352k,nr_inodes=1960838,mode=755 0 0
	devpts /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
	/usr/local/bin/autosshfs-map /home/root/mnt/ssh autofs rw,relatime,fd=12,pgrp=2373,timeout=600,minproto=5,maxproto=5,indirect 0 0
	/dev/sdb1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/home ext4 rw,relatime,data=ordered 0 0
	/usr/local/bin/autosshfs-map /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/home/rsi-bryan/mnt/ssh autofs rw,relatime,fd=6,pgrp=2373,timeout=600,minproto=5,maxproto=5,indirect 0 0
	/usr/local/bin/autosshfs-map /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/home/root/mnt/ssh autofs rw,relatime,fd=12,pgrp=2373,timeout=600,minproto=5,maxproto=5,indirect 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/tmp ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	tmpfs /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/run/shm tmpfs rw,nosuid,nodev 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2 ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	proc /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/proc proc rw,nosuid,nodev,noexec,relatime 0 0
	sysfs /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
	udev /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/dev devtmpfs rw,nosuid,relatime,size=7843352k,nr_inodes=1960838,mode=755 0 0
	devpts /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
	/dev/sdb1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/home ext4 rw,relatime,data=ordered 0 0
	/usr/local/bin/autosshfs-map /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/home/rsi-bryan/mnt/ssh autofs rw,relatime,fd=6,pgrp=2373,timeout=600,minproto=5,maxproto=5,indirect 0 0
	/usr/local/bin/autosshfs-map /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/home/root/mnt/ssh autofs rw,relatime,fd=12,pgrp=2373,timeout=600,minproto=5,maxproto=5,indirect 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/tmp ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	tmpfs /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/run/shm tmpfs rw,nosuid,nodev 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1 ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	proc /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/proc proc rw,nosuid,nodev,noexec,relatime 0 0
	sysfs /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
	udev /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/dev devtmpfs rw,nosuid,relatime,size=7843352k,nr_inodes=1960838,mode=755 0 0
	devpts /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
	/dev/sdb1 /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/home ext4 rw,relatime,data=ordered 0 0
	/usr/local/bin/autosshfs-map /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/home/rsi-bryan/mnt/ssh autofs rw,relatime,fd=6,pgrp=2373,timeout=600,minproto=5,maxproto=5,indirect 0 0
	/usr/local/bin/autosshfs-map /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/home/root/mnt/ssh autofs rw,relatime,fd=12,pgrp=2373,timeout=600,minproto=5,maxproto=5,indirect 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/tmp ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	tmpfs /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/run/shm tmpfs rw,nosuid,nodev 0 0
	tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1572916k,mode=700,uid=1000,gid=1000 0 0
	/home/rsi-bryan/.Private /home/rsi-bryan ecryptfs rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=b5199d66312ec438,ecryptfs_sig=d64cb6aff52617ca,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs 0 0
	gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0

Here it is sorted by device, and filtered to show only user-addressable block devices:

	/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33 ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/tmp ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2 ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/tmp ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1 ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	/dev/sda1 /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/tmp ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
	/dev/sdb1 /home ext4 rw,relatime,data=ordered 0 0
	/dev/sdb1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-amd64-9d864558-8c29-4d6a-b5a7-4d46e42d2c33/home ext4 rw,relatime,data=ordered 0 0
	/dev/sdb1 /var/lib/schroot/mount/click-ubuntu-sdk-15.04-armhf-dfd94c42-89ce-4574-a303-cb0039c184e2/home ext4 rw,relatime,data=ordered 0 0
	/dev/sdb1 /var/lib/schroot/mount/click-ubuntu-sdk-15.10-armhf-f9f62e36-5f0e-4f64-bc68-8a7a1f0530a1/home ext4 rw,relatime,data=ordered 0 0

**Comment by Fordi** [comment]
I've implemented the linux side of this in my fork (https://github.com/resin-io-modules/drivelist/compare/master...Fordi:master).  If you'd like me to work on the Mac or Windows side, I can do that, but I need to pull in machines I don't have easy access to for testing.

**Comment by lurch** [comment]
> As you can see, both /dev/sda1 and /dev/sdb1 are mounted at multiple points at the kernel level.

Looks like these are _all_ created by multiple schroots though, and I honestly don't think including chroots in the info reported by `drivelist` is useful?

Just out of curiosity, what does the current `scripts/linux.sh` from this repo report when run on your system?

**Comment by lurch** [comment]
> I've implemented the linux side of this in my fork

Looks interesting, but it's probably best to wait until #109 is merged before proceeding any further?

**Comment by jviotti** [comment]
@lurch @Fordi Thanks for the heads up. I didn't consider the scenario of a single partition having several mount-points, which can indeed be done in GNU/Linux, for example. 

The partition centric representation doesn't play very nice in Windows IMHO. In Windows, a drive can contain multiple partitions, but they can't be referred to in any way unless they are mounted as a drive letter (e.g: a mount-point), which means we can't describe partitions, just mount-points (the properties of `partitions` would be drive letters in this case, which are essentially mount-points). 

Since the core mission of `drivelist` is to provide a uniform interface among all operating systems it supports, representing the data in a way that makes sense everywhere is very valuable to us.

I propose the drive objects to remain mount-point centric, and include an array of paths where a drive is mounted in several locations. For example:

```
{
  device: '/dev/sdb',
  description: 'DataTraveler 2.0',
  size: 7823458304,
  mountpoints: [
    {
      partition: '/dev/sdb1'
      path: [ '/media/foo', '/media/bar' ]
    },
    {
      partition: '/dev/sdb2'
      path: [ '/media/baz' ]
    }
  ],
  raw: '/dev/sdb',
  protected: true,
  system: false
}
```

**Comment by jviotti** [comment]
Hm, actually the properties names from my example above doesn't make much sense. I guess that by renaming things a bit, we come close to what you suggested:

```js
{
  device: '/dev/sdb',
  description: 'DataTraveler 2.0',
  size: 7823458304,
  partitions: [
    {
      device: '/dev/sdb1'
      mountpoints: [ '/media/foo', '/media/bar' ]
    },
    {
      device: '/dev/sdb2'
      mountpoints: [ '/media/baz' ]
    }
  ],
  raw: '/dev/sdb',
  protected: true,
  system: false
}
```

**Comment by jviotti** [comment]
So I think the core issue is that we don't have a canonical way to reference/name partitions in a cross platform way. In UNIX based operating systems we can refer to the partition by using the path (e.g: `/dev/sda1`), or the mount-point (which can be many, so this is not an option). In Windows, in the other hand, we can only reference partitions by their mount-point (the drive letter, which AFAIK, will always be one).

**Comment by jviotti** [comment]
We have volume IDs in Windows (for example: `\\?\Volume{1b3b1146-4076-11e1-84aa-806e6f6e6963}\`), but I think that also refers to the whole drive, not to the partitions.

**Comment by jviotti** [comment]
`diskpart` is able to list unmounted partitions somehow, although it always refers to any unmounted partitions with an id of 0.

**Comment by jviotti** [comment]
Okay, looks like Volume GUIDs serve our purpose. Given Volume IDs are not very user friendly, I propose keeping `partitions` as an array. This also gives us to extra benefit of being able to maintain the order of the partitions in our data structure. For example: `drive.partitions[0]` will be the first partition of the drive.

**Comment by Fordi** [comment]
> In Windows, a drive can contain multiple partitions, but they can't be referred to in any way unless they are mounted as a drive letter

    C:\Users\homeuser> md C:\divide_by_zero
    C:\Users\homeuser> diskpart
    DISKPART> select volume c ; could be an index instead; just using 'c' as it should always work
    DISKPART> assign mount=C:\divide_by_zero
    DISKPART> exit
    C:\Users\homeuser> start C:\divide_by_zero

**Comment by Fordi** [comment]
> "We have volume IDs in Windows (for example: \\?\Volume{1b3b1146-4076-11e1-84aa-806e6f6e6963}\), but I think that also refers to the whole drive, not to the partitions."

In windows systems, a volume represents any block device.  It's essentially equivalent to /dev/sd*, except that the UUID there is unique to the physical device, not just an enumeration.

**Comment by Fordi** [comment]
Long run, I think I can just enumerate `SELECT * FROM Win32_MountPoint`, transform it all to YAML in JScript, and call it a day.

**Comment by lurch** [comment]
>  I didn't consider the scenario of a single partition having several mount-points, which can indeed be done in GNU/Linux, for example.

Indeed. Contrary to my earlier suspicion that this was some kind of schroot special-case-behaviour going on, I've just experimented and found that the plain `mount` command seemingly allows you to mount the same partition to multiple directories, with no 'preference' being given to one over the other.
```bash
$ mkdir /tmp/boot2
$ sudo mount /dev/sda1 /tmp/boot2/
$ mount | grep sda1
/dev/sda1 on /boot/efi type vfat (rw)
/dev/sda1 on /tmp/boot2 type vfat (rw)
```
You learn something new every day ;-)  Does OSX do the same / similar?

Been reading the other comments here too and it looks interesting but I've never looked at depth into how Windows deals with disks / volumes / partitions / mountpoints / etc.
@Fordi I don't want to risk bricking my only Windows machine - what does your `C:\divide_by_zero` example do?

> This also gives us to extra benefit of being able to maintain the order of the partitions in our data structure.

But obviously with the Primary / Extended / Logical partitioning of MBR, the order of partitions in the array _may_ not be the same as the physical order of partitions on disk ;)

> Since the core mission of drivelist is to provide a uniform interface among all operating systems it supports, representing the data in a way that makes sense everywhere is very valuable to us.

Yeah, given the core focus of this drivelist module, if there's certain info that we can't get for all three platforms, then maybe it should be excluded for all platforms?

**Comment by jviotti** [comment]
@Fordi Turns out neither `Win32_MountPoint` nor `Win32_Volume` are supported on Windows XP, which we still support due to Etcher (turns out there are a lot of XP users still).

> @Fordi I don't want to risk bricking my only Windows machine - what does your C:\divide_by_zero example do?

He's basically re-mounting `C:` as `C:\divide_by_zero` so `C:\divide_by_zero` also refers to the same volume as `C:`, which is very interesting!

***

I don't see an easy way forward here. Maybe worth still investigating if we can get a list of volumes from a physical drive (that represent the physical drive partitions)?

**Comment by jhermsmeier** [comment]
Closing, as the mountpoints have been restructured to the suggested format, i.e.;
```js
mountpoints: [
  { path: '/', label: 'Mac OS' },
  { path: '/private/var/vm', label: 'VM' }
]
```
